---
- hosts: "{{ hostGroup }}"
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
  - ../env_variables
  tasks:
  - name: Disabling Swap on all nodes
    shell: swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'

# Dsiable SELINUX, https://stackoverflow.com/questions/44253909/how-to-disable-selinux-on-ubuntu-with-ansible
  - name: enforce permissive until reboot
    shell: sudo setenforce 0 || exit 0

  - name: Disable SELinux
    selinux:
     state: disabled
