---
- hosts: "{{ hostGroup }}"
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
  - ../env_variables
  tasks:
  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  
  - name: Install Linux Network Tools
    shell: |
     yum install bridge-utils -y
     yum install telnet -y
     yum install iproute -y

  - name: Installing firewalld
    shell: |
     yum install firewalld -y
    tags:
    - disablefirewall

  - name: Installing Docker
    shell: |
     yum install -y yum-utils device-mapper-persistent-data lvm2
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     yum install docker-ce -y

  - name: Installing Kubernetes Releated Packages
    yum:
     name: "{{ packages }}"
     state: present

  - name: Reloading Daemon Changes 
    shell: |
     systemctl daemon-reload

  - name: Starting and Enabling the required Kube services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Starting and Enabling the Firewall Service
    service:
     name: "{{ firewall_service }}"
     state: started
     enabled: yes
    tags:
    - disablefirewall

  - name: Allow Network Ports in Firewalld on MASTER
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ master_ports }}"
    when: hostGroup == "KubeMasters"
    tags:
    - disablefirewall

  - name: Allow Network Ports in Firewalld on WORKERS
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ worker_ports }}"
    when: hostGroup == "KubeWorkers"
    tags: 
    - disablefirewall

  - name: Allow NodePorts on WORKERS, for Public Access
    firewalld:
     port: "{{ service_nodeports }}"
     zone: public
     state: enabled
     permanent: yes
     immediate: yes
    when: hostGroup == "KubeWorkers"
    tags:
    - disablefirewall

  - name: Allow NodePorts on MASTER, for Public Access
    firewalld:
     port: "{{ service_nodeports }}"
     zone: public
     state: enabled
     permanent: yes
     immediate: yes
    when: hostGroup == "KubeMasters"
    tags:
    - disablefirewall

  - name: Enabling Bridge Firewall Rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
